trigger:
  branches:
    include:
    - '*' # must quote since "*" is a YAML reserved character; we want a string

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 6 sdk'
  inputs:
    packageType: sdk
    version: 6.0.x

- task: UseDotNet@2
  displayName: 'Use .NET 7 sdk'
  inputs:
    packageType: sdk
    version: 7.0.x

- task: UseDotNet@2
  displayName: 'Use .NET 8 sdk'
  inputs:
    packageType: sdk
    version: 8.0.x

- task: UseDotNet@2
  displayName: 'Use .NET 9 sdk'
  inputs:
    packageType: sdk
    version: 9.0.x
    includePreviewVersions: true

- script: dotnet --info
  displayName: 'dotnet info'

- powershell: ./build.ps1
  displayName: 'Powershell Script'
  env:
    NuGet__ApiKey: $(nugetApiKey)
    NuGet__SourceUrl: $(nugetSourceUrl)
