name: dotnetcore

on: [push]

jobs:
  # Label of the container job
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET SDK
      uses: WeihanLi/dotnet-install@v0.3.0
      with:
        version: |
          8.0.x
          9.0.x
          10.0.x
    - name: dotnet info
      run: dotnet --info
    - name: build
      run: bash ./build.sh
